import {CloudAPI,friendly} from './api.js';
import {authEmail,uuid,safeSnapshot,validateDraft,receiptMessage,SubmissionState} from './model.js';
import {parseSubmissionJson,parseSubmissionXlsx} from './submission-input.js';
import {reviewPdfFile} from './pdf-review.js?v=20261006-student-design-2';
const api=new CloudAPI(),state=new SubmissionState(),$=id=>document.getElementById(id),h=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
let logged=false,claimed='',working=false,epoch=0,authBusy=false,pdfAbort=null,selectedFile=null,manualBackup=null,manualMode=false,deskUndo=null;
const status=s=>$('status').textContent=s;
function fileStatus(message,phase='idle'){ $('file-status').textContent=message; $('file-status').dataset.state=phase; $('file-status').setAttribute('aria-busy',String(phase==='reading')); }
function exitManual(){deskUndo=null;manualMode=false;manualBackup=null;$('cancel-manual').hidden=true;$('manual').hidden=false;}

const target=()=>{const courseId=$('course').value.trim(),baseVersion=Number($('version').value);if(courseId!==claimed||!uuid(courseId)||!Number.isSafeInteger(baseVersion)||baseVersion<1)throw Error('수업과 기준 버전을 확인하세요.');return {courseId,baseVersion};};
function controls(){const lock=working||!!state.retry;$('draft-fields').disabled=lock;$('claim-button').disabled=lock;$('course').disabled=lock;$('courses').disabled=lock;$('final-confirm').disabled=lock||!state.layout;$('submit').disabled=working||!state.layout||(!state.retry&&!$('final-confirm').checked);$('new-request').hidden=!state.retry;$('new-request').disabled=working;$('submit').textContent=state.retry?'같은 접수번호로 다시 보내기':'검토한 자리 정보 제출';}
function invalidate(){state.invalidate();$('final-confirm').checked=false;$('validation').textContent='수정 내용을 다시 대조하고 최종 확인하세요.';controls();}
function grid(){const p=state.layout;if(!p)return;$('layout-editor').hidden=false;$('rows').value=p.rows;$('cols').value=p.cols;$('board').value=p.boardSide;const positions=new Map(p.cells.map(c=>[c.row+':'+c.col,c]));p.cells=Array.from({length:p.rows*p.cols},(_,i)=>positions.get((Math.floor(i/p.cols)+1)+':'+(i%p.cols+1))||{row:Math.floor(i/p.cols)+1,col:i%p.cols+1,kind:'void',studentNumber:''});const board='<div class="board">원본 교탁 위치</div>';$('preview').innerHTML=(p.boardSide==='top'?board:'')+`<div class="grid" style="--cols:${p.cols};grid-template-columns:repeat(${p.cols},130px)">${p.cells.map((c,i)=>`<div class="cell ${c.kind}"><small>${c.row}행 ${c.col}열</small><label><span class="sr-only">공간</span><select data-i="${i}" data-field="kind" aria-label="${c.row}행 ${c.col}열 공간">${['desk','aisle','void'].map((k,j)=>`<option value="${k}" ${c.kind===k?'selected':''}>${['책상','통로','제외'][j]}</option>`).join('')}</select></label><input data-i="${i}" data-field="studentNumber" value="${h(c.studentNumber)}" inputmode="numeric" maxlength="5" placeholder="학번 입력" aria-label="${c.row}행 ${c.col}열 전체 5자리 학번" aria-describedby="seat-number-help" ${c.kind!=='desk'?'disabled':''}>${addDeskControls(c,i)}</div>`).join('')}</div>`+(p.boardSide==='bottom'?board:'');invalidate();placement();}
// Add one desk next to a reference desk. Outside the grid, a row/column is added; new filler spaces are 'void'.
const DIRS={up:[-1,0,'위','↑'],left:[0,-1,'왼쪽','←'],right:[0,1,'오른쪽','→'],down:[1,0,'아래','↓']};
function addDeskControls(c,i){return `<button type="button" class="add-desk" data-add="${i}" aria-label="${c.row}행 ${c.col}열 옆에 책상 추가" title="이 책상 옆에 책상 추가">+</button><div class="add-picker" role="group" aria-label="${c.row}행 ${c.col}열 기준 추가 방향">${Object.entries(DIRS).map(([d,[,,label,arrow]])=>`<button type="button" class="dir-${d}" data-dir="${d}" data-from="${i}" aria-label="${label}쪽에 책상 추가">${arrow}</button>`).join('')}<button type="button" class="dir-cancel" data-add-cancel aria-label="책상 추가 취소">✕</button></div>`;}
function addDesk(i,dir){const p=state.layout,src=p.cells[i],[dr,dc,label]=DIRS[dir];let row=src.row+dr,col=src.col+dc,rows=p.rows,cols=p.cols;const cells=p.cells.map(c=>({...c}));
 if(row<1||row>rows||col<1||col>cols){if((dr&&rows>=30)||(dc&&cols>=30)){status('행과 열은 최대 30칸까지 늘릴 수 있습니다.');return;}if(dr)rows++;else cols++;if(row<1){cells.forEach(c=>c.row++);row=1;}if(col<1){cells.forEach(c=>c.col++);col=1;}}
 const target=cells.find(c=>c.row===row&&c.col===col);
 if(target?.kind==='desk'){status(`${label}쪽(${row}행 ${col}열)에는 이미 책상이 있습니다.`);return;}
 if(target?.kind==='aisle'){status(`${label}쪽(${row}행 ${col}열)은 통로라 책상을 추가할 수 없습니다. 통로를 바꾸려면 그 칸의 공간을 직접 고르세요.`);return;}
 if(target){target.kind='desk';target.studentNumber='';}else cells.push({row,col,kind:'desk',studentNumber:''});
 const before=structuredClone(p);state.layout={...p,rows,cols,cells};grid();deskUndo={before,from:{row:src.row,col:src.col},key:JSON.stringify(state.layout)};placement();status(`${row}행 ${col}열에 책상을 추가했습니다. 학번을 입력하거나 빈자리로 두세요.`);
 $('preview').querySelector(`input[data-i="${state.layout.cells.findIndex(c=>c.row===row&&c.col===col)}"]`)?.focus();}
// Display only: placement progress and cells that validateDraft would reject.
function seatProblems(cells){const numbers=state.snapshot?.numbers,counts=new Map();for(const c of cells)if(c.kind==='desk'&&c.studentNumber)counts.set(c.studentNumber,(counts.get(c.studentNumber)||0)+1);return cells.map(c=>c.kind!=='desk'||!c.studentNumber?'':!/^\d{5}$/.test(c.studentNumber)?'학번 5자리 확인':counts.get(c.studentNumber)>1?'중복 학번':numbers&&!numbers.includes(c.studentNumber)?'미등록 학번':'');}
function placement(){renderDeskUndo();const p=state.layout,box=$('placement');if(!p){box.replaceChildren();return;}const problems=seatProblems(p.cells),numbers=state.snapshot?.numbers;
 $('preview').querySelectorAll('.cell').forEach((n,i)=>{n.classList.toggle('problem',!!problems[i]);const input=n.querySelector('input');input.setAttribute('aria-invalid',String(!!problems[i]));if(problems[i])input.title=problems[i];else input.removeAttribute('title');});
 const filled=p.cells.filter(c=>c.kind==='desk'&&c.studentNumber),empty=p.cells.filter(c=>c.kind==='desk'&&!c.studentNumber).length,issues=p.cells.map((c,i)=>[c,problems[i]]).filter(([,r])=>r);
 if(!numbers){box.innerHTML=`<div class="placement-head"><strong>배치 ${filled.length}명</strong><span>빈 책상 ${empty}칸</span></div>`;return;}
 const placed=new Set(filled.map(c=>c.studentNumber).filter(n=>numbers.includes(n))),missing=numbers.filter(n=>!placed.has(n)),pct=numbers.length?Math.round(placed.size/numbers.length*100):0;
 box.innerHTML=`<div class="placement-head"><strong>배치 ${placed.size} / ${numbers.length}명</strong><span class="placement-bar" aria-hidden="true"><i style="width:${pct}%"></i></span><span>빈 책상 ${empty}칸</span></div>${missing.length?`<p><b>미배치 학번</b> ${missing.map(n=>`<span class="chip missing">${h(n)}</span>`).join('')}</p>`:'<p class="placement-ok">등록된 학번이 모두 배치되었습니다.</p>'}${issues.length?`<p><b>확인 필요</b> ${issues.map(([c,r])=>`<span class="chip problem">${c.row}행 ${c.col}열 · ${h(r)} ${h(c.studentNumber)}</span>`).join('')}</p>`:''}`;}
// The last single-desk add can be undone until anything else in the layout changes.
function renderDeskUndo(){let b=$('undo-add-desk');const valid=!!deskUndo&&!!state.layout&&JSON.stringify(state.layout)===deskUndo.key;if(!valid){b?.remove();return;}if(b)return;b=document.createElement('button');b.type='button';b.id='undo-add-desk';b.className='desk-undo';b.textContent='방금 추가한 책상 취소';b.onclick=()=>{if(working||state.retry||!deskUndo)return;const {before,from}=deskUndo;deskUndo=null;state.layout=before;grid();status('방금 추가한 책상을 취소했습니다.');$('preview').querySelector(`[data-add="${state.layout.cells.findIndex(c=>c.row===from.row&&c.col===from.col)}"]`)?.focus();};$('preview').before(b);}
function clearDraft(){selectedFile=null;exitManual();$('retry-file').hidden=true;fileStatus('PDF를 선택하세요. 원본 파일·이름·사진은 전송하지 않습니다.');state.reset();$('layout-editor').hidden=true;$('preview').replaceChildren();$('file').value='';$('final-confirm').checked=false;$('receipt').textContent='';$('validation').textContent='';controls();}
async function courses(){if(!api.config.studentSnapshots)return;const g=epoch;try{const list=await api.rpc('hafs_student_courses');if(g!==epoch)return;$('courses').innerHTML='<option value="">선택하세요</option>'+list.filter(x=>uuid(x.id)).map(x=>`<option value="${x.id}">${h(x.name)}</option>`).join('');$('courses-label').hidden=false;if(!list.length)status('현재 지정된 수업이 없습니다. 선생님이 대표 학번을 등록한 뒤 다시 로그인하세요.');}catch(e){if(g===epoch)status(friendly(e));}}
$('courses').onchange=()=>{if(working||state.retry)return;$('course').value=$('courses').value;claimed='';clearDraft();$('editor').hidden=true;};
$('course').oninput=()=>{claimed='';clearDraft();$('editor').hidden=true;};
$('auth').onsubmit=async e=>{e.preventDefault();if(authBusy)return;authBusy=true;const g=epoch;$('login').disabled=true;try{const id=$('email').value.trim();if(api.config.authMode==='password'){let password=$('password').value;$('password').value='';const signingIn=api.signInPassword(authEmail(id,api.config),password);password='';await signingIn;}else await api.verifyCode(id,$('code').value.trim());if(g!==epoch)return;logged=true;$('auth-panel').hidden=true;$('workspace').hidden=false;$('logout').hidden=false;status('로그인했습니다. 제출할 수업의 대표 권한을 확인하세요.');await courses();}catch(e){if(g===epoch)status(friendly(e));}finally{authBusy=false;$('login').disabled=false;}};
$('send-code').onclick=async()=>{if(authBusy)return;authBusy=true;$('send-code').disabled=true;try{await api.sendCode($('email').value.trim());status('등록된 계정이면 인증 코드가 전송됩니다.');}catch(e){status(friendly(e));}finally{authBusy=false;$('send-code').disabled=false;}};
$('logout').onclick=async()=>{epoch++;pdfAbort?.abort();pdfAbort=null;logged=false;claimed='';working=false;clearDraft();for(const id of ['course','class-label','version','prefix','email'])$(id).value='';$('courses').replaceChildren();$('numbers').textContent='';$('course-status').textContent='';$('editor').hidden=true;$('workspace').hidden=true;$('auth-panel').hidden=false;$('logout').hidden=true;$('password').value='';$('code').value='';status('로그아웃했습니다.');await api.logout();};
$('claim').onsubmit=async e=>{e.preventDefault();if(working||state.retry||!logged)return;const course=$('course').value.trim();if(!uuid(course)){status('배부받은 수업 코드를 확인하세요.');return;}working=true;controls();const g=epoch;try{const claim=await api.rpc('hafs_claim_representative',{p_course:course});if(g!==epoch)return;if(claim?.authorized!==true)throw Error('대표 권한을 확인하지 못했습니다.');claimed=course;clearDraft();if(api.config.studentSnapshots){const raw=await api.rpc('hafs_student_snapshot',{p_course:course});if(g!==epoch)return;state.snapshot=safeSnapshot(raw);if(state.snapshot.id!==course)throw Error('수업 정보가 일치하지 않습니다.');$('version').value=state.snapshot.version;$('version').readOnly=true;$('class-label').value=state.snapshot.name;const prefixes=[...new Set(state.snapshot.numbers.map(n=>n.slice(0,3)))];$('prefix').value=prefixes.length===1?prefixes[0]:'';$('numbers').textContent='등록 학번: '+state.snapshot.numbers.join(', ');$('current-layout').hidden=!state.snapshot.layout;}else{$('version').readOnly=false;$('version').value='';$('numbers').textContent='선생님이 배부한 학번 목록 및 기준 버전과 대조하세요.';} $('editor').hidden=false;$('course-status').textContent='대표 확인 완료';status('자리표를 준비하세요.');}catch(e){if(g===epoch){claimed='';$('editor').hidden=true;status(friendly(e));}}finally{if(g===epoch){working=false;controls();}}};
$('manual').onclick=()=>{if(working||state.retry||manualMode)return;manualBackup=state.layout?structuredClone(state.layout):null;manualMode=true;$('cancel-manual').hidden=false;$('manual').hidden=true;state.layout={rows:5,cols:6,boardSide:'bottom',cells:Array.from({length:30},(_,i)=>({row:Math.floor(i/6)+1,col:i%6+1,kind:'desk',studentNumber:''}))};grid();fileStatus('직접 입력 중입니다. 취소하면 이전 배치로 돌아가 PDF를 선택할 수 있습니다.');};
$('cancel-manual').onclick=()=>{if(working||state.retry)return;state.layout=manualBackup;exitManual();if(state.layout)grid();else{$('layout-editor').hidden=true;$('preview').replaceChildren();invalidate();}fileStatus('직접 입력을 취소했습니다. 자리표 PDF를 불러오세요.');$('review-file').focus();};
$('current-layout').onclick=()=>{if(!working&&!state.retry&&state.snapshot?.layout){exitManual();state.layout=structuredClone(state.snapshot.layout);grid();fileStatus('현재 자리표를 불러왔습니다. 원본과 대조하고 최종 확인하세요.','success');}};
$('resize').onclick=()=>{const rows=Number($('rows').value),cols=Number($('cols').value);if(!Number.isInteger(rows)||!Number.isInteger(cols)||rows<1||cols<1||rows>30||cols>30){status('행과 열은 1~30 사이 정수로 입력하세요.');return;}if(state.layout.cells.some(c=>(c.row>rows||c.col>cols)&&c.studentNumber)&&!confirm('줄어드는 영역의 학번이 지워집니다. 계속할까요?'))return;state.layout={...state.layout,rows,cols,cells:state.layout.cells.filter(c=>c.row<=rows&&c.col<=cols)};grid();};
$('board').onchange=()=>{state.layout.boardSide=$('board').value;grid();};
$('preview').onclick=e=>{const b=e.target.closest('button');if(!b||working||state.retry||!state.layout)return;const cell=b.closest('.cell');if(b.dataset.add!==undefined){$('preview').querySelectorAll('.cell.picking').forEach(n=>n.classList.remove('picking'));cell.classList.add('picking');cell.querySelector('[data-dir=up]').focus();}else if(b.dataset.dir)addDesk(Number(b.dataset.from),b.dataset.dir);else if(b.dataset.addCancel!==undefined){cell.classList.remove('picking');cell.querySelector('.add-desk').focus();}};
$('preview').oninput=e=>{deskUndo=null;const t=e.target;if(!t.dataset.field)return;const c=state.layout.cells[Number(t.dataset.i)];if(t.dataset.field==='studentNumber')c.studentNumber=t.value.trim();else{c.kind=t.value;if(c.kind!=='desk')c.studentNumber='';const input=t.closest('.cell').querySelector('input');input.disabled=c.kind!=='desk';input.value=c.studentNumber;t.closest('.cell').className='cell '+c.kind;}invalidate();placement();};
for(const id of ['version','class-label','prefix'])$(id).onchange=()=>invalidate();
$('review-file').onclick=()=>{if(!working&&!state.retry)$('file').click();};
$('retry-file').onclick=()=>readSelectedFile();
$('file').onchange=()=>{const file=$('file').files?.[0];$('file').value='';if(!file){fileStatus('파일 선택을 취소했습니다. 기존 배치는 그대로입니다.');return;}selectedFile=file;void readSelectedFile();};
$('file').oncancel=()=>fileStatus('파일 선택을 취소했습니다. 기존 배치는 그대로입니다.');
async function readSelectedFile(){
 if(working||state.retry||!selectedFile)return;
 const file=selectedFile;working=true;$('final-confirm').checked=false;controls();$('retry-file').hidden=true;
 const g=epoch,sg=++state.generation;fileStatus('파일을 읽는 중입니다… 잠시 기다려 주세요.','reading');
 try{const t=target();let p;
  if(/\.pdf$/i.test(file.name)){
   if(!/^\d{3}$/.test($('prefix').value)||!$('class-label').value.trim())throw Error('위 학급명과 학번 접두 3자리를 입력한 뒤 “선택한 파일 다시 읽기”를 누르세요.');
   pdfAbort=new AbortController();p=await reviewPdfFile(file,{prefix:$('prefix').value,classLabel:$('class-label').value.trim(),numbers:state.snapshot?.numbers},{remote:true,continueLabel:'이 배치로 미리보기',signal:pdfAbort.signal,onReady:()=>{if(g===epoch)fileStatus('PDF 읽기 완료 · 열린 검토창에서 번호·빈자리·통로·교탁을 확인하세요.','review');}});pdfAbort=null;
  }else if(/\.xlsx$/i.test(file.name)){if(file.size>5*1024*1024)throw Error('XLSX는 5MB 이하만 지원합니다.');p=parseSubmissionXlsx(new Uint8Array(await file.arrayBuffer()),t);}
  else if(/\.json$/i.test(file.name)){if(file.size>200000)throw Error('JSON은 200KB 이하만 지원합니다.');p=parseSubmissionJson(await file.text(),t);}
  else throw Error('PDF / XLSX / JSON 파일을 선택하세요.');
  if(g!==epoch||sg!==state.generation)return;
  if(!p){fileStatus('PDF 검토를 취소했습니다. 기존 배치는 그대로입니다.');$('retry-file').hidden=false;return;}
  exitManual();state.layout=p;grid();fileStatus('불러오기 완료 · 아래 미리보기를 원본과 대조한 뒤 최종 확인하고 제출하세요.','success');status('자리표를 불러왔습니다. 아직 제출되지 않았습니다.');
 }catch(e){if(g===epoch){fileStatus('불러오기 실패 · '+friendly(e)+' 기존 배치는 유지됩니다.','error');$('retry-file').hidden=false;}}
 finally{if(g===epoch){pdfAbort=null;working=false;controls();}}
}
$('final-confirm').onchange=()=>{try{if($('final-confirm').checked){validateDraft(state.layout,state.snapshot?.numbers);target();$('validation').textContent='검증 통과 · 학번과 자리 좌표만 전송합니다.';}}catch(e){$('final-confirm').checked=false;$('validation').textContent=e.message;}controls();};
$('submit').onclick=async()=>{if(working||!logged||(!state.retry&&!$('final-confirm').checked))return;working=true;const g=epoch;try{if(!state.retry)state.layout=validateDraft(state.layout,state.snapshot?.numbers);const request=state.request(target());controls();const receipt=await api.rpc('hafs_submit_layout',request);if(g!==epoch)return;let result=receipt;if(api.config.studentSnapshots){try{const detail=await api.rpc('hafs_student_receipt',{p_course:claimed,p_receipt:receipt.receipt});if(g!==epoch)return;result={...receipt,...detail};}catch{/* The confirmed receipt remains valid even if status lookup fails. */}}const message=receiptMessage(result);state.retry=null;state.layout=null;$('layout-editor').hidden=true;$('file').value='';$('final-confirm').checked=false;$('receipt').textContent=message;$('validation').textContent='';status('제출을 접수했습니다. 새 제출 전 대표 권한 확인으로 최신 기준을 다시 불러오세요.');claimed='';$('course-status').textContent='새 제출 전 대표 권한을 다시 확인하세요.';}catch(e){if(g===epoch){status(state.retry?'접수 여부를 확인하지 못했습니다. 같은 요청으로 다시 보내면 중복 접수를 방지합니다.':friendly(e));$('receipt').textContent=state.retry?'요청 ID: '+state.retry.p_request+'\n새 제출을 만들기 전에 선생님께 접수 여부를 확인하세요.':'';}}finally{if(g===epoch){working=false;controls();}}};
$('new-request').onclick=()=>{if(working||!confirm('선생님께 이전 요청 접수 여부를 확인했나요? 새 요청은 별도 제출로 접수될 수 있습니다.'))return;const snapshot=state.snapshot;clearDraft();state.snapshot=snapshot;status('새 제출을 준비합니다. 최신 기준 버전인지 확인하세요.');};
window.addEventListener('beforeunload',e=>{if(state.layout||state.retry){e.preventDefault();e.returnValue='';}});
try{await api.init();if(api.config.authMode!=='password'||api.config.studentSnapshots!==true)throw Error('학생 계정 연결 설정이 필요합니다. 선생님께 문의하세요.');authEmail('00000',api.config);const pw=true;$('otp-fields').hidden=pw;$('password-field').hidden=!pw;if(pw){$('email').type='text';$('email').inputMode='numeric';$('email').maxLength=5;$('email').parentElement.firstChild.textContent='학번';$('auth-panel').querySelector('p').textContent='선생님이 지정한 대표 학번과 배부받은 비밀번호로 로그인하세요.';} $('login').disabled=false;$('send-code').disabled=false;status('지정된 대표 계정으로 로그인하세요.');}catch(e){status(friendly(e));}
