export class APIError extends Error{constructor(code,status=0){super(code);this.code=code;this.status=status;}}
export class CloudAPI{
 constructor(){this.access='';this.refresh='';this.expires=0;this.refreshing=null;this.generation=0;}
 async init(){const r=await fetch(new URL('./config.json',import.meta.url),{cache:'no-store'});if(!r.ok)throw Error('서버 설정을 읽을 수 없습니다.');this.config=await r.json();if(this.config.enabled!==true||!/^https:\/\/[a-z0-9-]+\.supabase\.co$/.test(this.config.supabaseUrl)||!this.config.publishableKey?.startsWith('sb_publishable_'))throw Error('서버 설정이 완료되지 않았습니다.');}
 async request(path,body,token){const c=new AbortController(),t=setTimeout(()=>c.abort(),15000);try{const r=await fetch(this.config.supabaseUrl+path,{method:'POST',headers:{'Content-Type':'application/json',apikey:this.config.publishableKey,...(token?{Authorization:'Bearer '+token}:{})},body:JSON.stringify(body),signal:c.signal,cache:'no-store'});const j=await r.json().catch(()=>({}));if(!r.ok)throw new APIError(j.error_code??j.message??j.error_description??j.error??j.code??`HTTP_${r.status}`,r.status);return j;}catch(e){if(e.name==='AbortError')throw new APIError('요청 시간이 초과되었습니다. 저장 여부가 불확실하니 새로고침으로 확인한 뒤 다시 시도하세요.');throw e;}finally{clearTimeout(t);}}
 session(s){if(!s.access_token||!s.refresh_token)throw Error('로그인이 완료되지 않았습니다.');this.access=s.access_token;this.refresh=s.refresh_token;this.expires=Date.now()+(s.expires_in||3600)*1000;}
 async signInPassword(email,password){const g=++this.generation;const body={email,password};password='';let pending;try{pending=this.request('/auth/v1/token?grant_type=password',body);}finally{body.password='';}const s=await pending;if(g!==this.generation)throw new APIError('취소된 로그인입니다.',401);this.session(s);}
 async rpc(name,args={}){const epoch=this.generation;if(!this.access)throw new APIError('로그인이 필요합니다.',401);if(Date.now()>this.expires-60000){if(!this.refreshing){const g=this.generation;this.refreshing=this.request('/auth/v1/token?grant_type=refresh_token',{refresh_token:this.refresh}).then(s=>{if(g===this.generation)this.session(s);else throw new APIError('로그아웃되었습니다.',401);}).finally(()=>this.refreshing=null);}await this.refreshing;}if(epoch!==this.generation)throw new APIError('로그아웃되었습니다.',401);const result=await this.request('/rest/v1/rpc/'+name,args,this.access);if(epoch!==this.generation)throw new APIError('로그아웃되었습니다.',401);return result;}
 async logout(){const a=this.access;this.generation++;this.access='';this.refresh='';this.expires=0;if(a)await this.request('/auth/v1/logout',{},a).catch(()=>{});}
}
export const friendly=e=>{const msg=e?.message||String(e);const codes={invalid_credentials:'ID 또는 비밀번호를 확인하세요.',email_not_confirmed:'계정 활성화가 완료되지 않았습니다. 관리자에게 확인하세요.',STALE_VERSION:'다른 기기에서 자료가 바뀌었습니다. 새로고침한 뒤 다시 검토해 주세요.',NOT_AUTHORIZED:'이 학급의 접근 권한이 없거나 만료되었습니다.',AUTH_USER_INACTIVE:'계정이 비활성 상태입니다. 관리자에게 확인해 주세요.',INCOMPLETE_ROSTER:'모든 재적 학생을 한 번씩 자리표에 배치해 주세요.',DUPLICATE_IDENTITY:'중복 학번 또는 다른 학급 학생 ID입니다.',INVALID_ROSTER:'명렬 형식을 확인해 주세요.',UNKNOWN_STUDENT:'현재 반에 등록되지 않은 학생입니다.',PGRST202:'필요한 서버 기능이 아직 배포되지 않았습니다.'};for(const [k,v]of Object.entries(codes))if(msg.includes(k))return v;return e instanceof APIError?(e.status===401?'로그인이 만료되었습니다. 다시 로그인하세요.':e.status===429?'요청이 많습니다. 잠시 후 다시 시도하세요.':e.status===0?'연결을 확인하지 못했습니다. 저장 여부를 새로고침으로 확인한 뒤 다시 시도하세요.':'요청을 완료하지 못했습니다. 입력값과 접근 권한을 확인하세요.'):msg;};
