import {parseRoster,csvEncode} from './core.js';
import {importRosterXlsx,makeWorkbook,XLSX_MIME,importLayoutXlsx,makeLayoutWorkbook} from './excel.js';
export {csvEncode,makeWorkbook,XLSX_MIME,makeLayoutWorkbook};
export const h=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
export const uuid=()=>crypto.randomUUID();
export function student(number,name){number=String(number).trim();name=String(name).trim();if(!/^[A-Za-z0-9_-]{1,30}$/.test(number))throw Error('학번은 영문·숫자·_·- 1~30자로 입력하세요.');if(!name||name.length>50)throw Error('이름은 1~50자로 입력하세요.');return {number,name};}
export function validateRoster(rows){if(!Array.isArray(rows)||rows.length>500)throw Error('한 반에 500명 이하만 저장할 수 있습니다.');const nums=new Set(),ids=new Set();return rows.map(r=>{const clean=student(r.number,r.name);if(!r.id||nums.has(clean.number)||ids.has(r.id))throw Error('중복 학번 또는 학생이 있습니다.');nums.add(clean.number);ids.add(r.id);return {id:r.id,...clean};});}
export async function rosterFile(file){if(file.size>5*1024*1024)throw Error('명렬 파일은 5MB 이하만 열 수 있습니다.');if(/\.xlsx$/i.test(file.name))return importRosterXlsx(new Uint8Array(await file.arrayBuffer()));if(!/\.csv$/i.test(file.name))throw Error('CSV 또는 XLSX 양식을 사용하세요.');return parseRoster(await file.text());}
export function planImport(existing,rows){const active=existing.filter(x=>x.active),all=[...active],added=[],same=[],conflicts=[];const inputs=new Set();for(const r of rows){if(inputs.has(r.number))throw Error('중복 학번이 있습니다.');inputs.add(r.number);const found=active.find(x=>x.number===r.number);if(found){if(found.name===r.name)same.push(found);else conflicts.push({...r,previous:found.name});}else{const old=existing.find(x=>!x.active&&x.number===r.number);if(old)conflicts.push({...r,previous:old.name,inactive:true});else{const n={id:uuid(),...r,active:true};all.push(n);added.push(n);}}}return {all,added,same,conflicts};}
export function blankLayout(rows=4,cols=8){return {rows,cols,boardSide:'bottom',cells:Array.from({length:rows*cols},(_,i)=>({row:Math.floor(i/cols)+1,col:i%cols+1,kind:'desk',studentNumber:''}))};}
export function fromSnapshot(s){return {...s.layout,cells:s.layout.cells.map(c=>({row:c.row,col:c.col,kind:c.kind,studentNumber:s.students.find(x=>x.id===c.studentId)?.number??''}))};}
export function validateLayout(l,students){if(!l||!Array.isArray(l.cells)||!['top','bottom'].includes(l.boardSide))throw Error('교실 배치 형식 또는 칠판 방향 오류');if(!Number.isInteger(l.rows)||!Number.isInteger(l.cols)||l.rows<1||l.rows>30||l.cols<1||l.cols>30)throw Error('교실 크기는 1~30행·열로 입력하세요.');if(l.cells.length!==l.rows*l.cols)throw Error('모든 공간을 포함해 주세요.');const seen=new Set(),pos=new Set();for(const c of l.cells){if(!Number.isInteger(c.row)||!Number.isInteger(c.col)||c.row<1||c.row>l.rows||c.col<1||c.col>l.cols||pos.has(`${c.row}:${c.col}`))throw Error('자리 좌표가 중복되거나 범위를 벗어났습니다.');pos.add(`${c.row}:${c.col}`);if(!['desk','aisle','void'].includes(c.kind))throw Error('자리 유형 오류');if(c.studentNumber){if(c.kind!=='desk'||!students.some(s=>s.number===c.studentNumber)||seen.has(c.studentNumber))throw Error('미등록·중복 학번 또는 통로에 배치된 학생이 있습니다.');seen.add(c.studentNumber);}}if(seen.size!==students.length)throw Error(`모든 재적 학생을 한 번씩 배치하세요. 현재 ${seen.size}/${students.length}명`);return l;}
export function parserCourse(s){return {id:s.id,classId:s.id,termId:'2026-2',version:s.version,rows:s.layout.rows,cols:s.layout.cols,boardSide:s.layout.boardSide,spaces:s.layout.cells.filter(x=>x.kind!=='desk').map(({row,col,kind})=>({row,col,kind})),roster:s.students.map(x=>({studentId:x.id,number:x.number,active:true})),seats:s.layout.cells.filter(x=>x.studentId).map(({row,col,studentId})=>({row,col,studentId})),rules:[{min:0,score:0}]};}
export async function seatFile(file,s){if(file.size>5*1024*1024)throw Error('자리표는 5MB 이하만 지원합니다.');if(!/\.xlsx$/i.test(file.name))throw Error('현재 웹 관리자는 XLSX 양식을 지원합니다.');const c=parserCourse(s),l=importLayoutXlsx(new Uint8Array(await file.arrayBuffer()),c);return {rows:l.rows,cols:l.cols,boardSide:l.boardSide,cells:Array.from({length:l.rows*l.cols},(_,i)=>{const row=Math.floor(i/l.cols)+1,col=i%l.cols+1;const seat=l.seats.find(x=>x.row===row&&x.col===col);return {row,col,kind:l.spaces?.find(x=>x.row===row&&x.col===col)?.kind??'desk',studentNumber:seat?s.students.find(x=>x.id===seat.studentId).number:''};})};}
export async function portrait(file){if(!['image/jpeg','image/png','image/webp'].includes(file.type)||file.size>8*1024*1024)throw Error('8MB 이하 JPEG·PNG·WebP 사진만 선택하세요.');const bmp=await createImageBitmap(file);try{if(bmp.width>12000||bmp.height>12000)throw Error('사진 크기가 너무 큽니다.');const c=document.createElement('canvas'),k=Math.min(1,240/Math.max(bmp.width,bmp.height));c.width=Math.max(1,Math.round(bmp.width*k));c.height=Math.max(1,Math.round(bmp.height*k));c.getContext('2d').drawImage(bmp,0,0,c.width,c.height);const data=c.toDataURL('image/jpeg',.8);if(data.length>100023)throw Error('축소 사진이 75KB를 넘습니다. 더 작은 사진을 선택하세요.');return data;}finally{bmp.close();}}
