import {makeSheetGrid,normalizedRegion,dragRegion,photoMapping,createSheetLoader,createPhotoUpload,MAX_REGIONS} from './photo-sheet-core.js';
import {loadSheetSource,cropPortrait} from './photo-sheet-source.js';
const h=value=>String(value??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const defaultGrid=()=>({rows:7,cols:5,bounds:{x:0,y:0,width:100,height:100},inset:{x:10,y:5,width:80,height:70}});
/** All originals, crops and names stay in this ephemeral view until explicit final upload. */
export function mountPhotoSheet(root,options){
  const {courseId,courseName,version,students,existingIds=[]}=options;
  let disposed=false,source=null,file=null,regions=[],grid=defaultGrid(),phase='pick',loading=false,uploading=false,message='',drag=null,serial=0,review=[],result=null,confirmed=false,openedRegionKey=null;
  const isCurrent=()=>!disposed&&root.isConnected&&options.isCurrent();
  const loader=createSheetLoader({decode:options.decode??loadSheetSource,isCurrent});
  const q=selector=>root.querySelector(selector);
  const fields=(object,prefix)=>[['x','왼쪽'],['y','위쪽'],['width','너비'],['height','높이']].map(([key,label])=>`<label>${label} %<input type="number" min="0" max="100" step="0.1" data-${prefix}="${key}" value="${object[key]}"></label>`).join('');
  const labelOf=p=>`${p.student.number} ${p.student.name}`;
  function error(e){message=e.message??String(e);render();}
  function draw(){const canvas=q('[data-sheet-canvas]');if(!canvas||!source)return;const scale=Math.min(1,1200/source.width);canvas.width=Math.round(source.width*scale);canvas.height=Math.round(source.height*scale);const ctx=canvas.getContext('2d');ctx.drawImage(source.canvas,0,0,canvas.width,canvas.height);for(const [i,r] of regions.entries()){const x=r.x/100*canvas.width,y=r.y/100*canvas.height,w=r.width/100*canvas.width,hh=r.height/100*canvas.height;ctx.strokeStyle=r.skip?'#64748b':r.id?'#08764d':'#b45309';ctx.lineWidth=3;ctx.strokeRect(x,y,w,hh);ctx.fillStyle=ctx.strokeStyle;ctx.fillRect(x,y,Math.min(w,42),23);ctx.fillStyle='#fff';ctx.font='bold 16px sans-serif';ctx.fillText(String(i+1),x+4,y+17);}if(drag?.to){const a=drag.from,b=drag.to;ctx.strokeStyle='#007fb1';ctx.lineWidth=3;ctx.setLineDash([8,5]);ctx.strokeRect(Math.min(a.x,b.x)/100*canvas.width,Math.min(a.y,b.y)/100*canvas.height,Math.abs(a.x-b.x)/100*canvas.width,Math.abs(a.y-b.y)/100*canvas.height);}}
  function render(){
    if(!isCurrent())return;
    root.innerHTML=`<section class="panel photo-sheet" aria-label="학급 사진 명렬표 가져오기"><header><div><span class="badge">사진 명렬표 한 장으로 시작</span><h2>학급 사진 명렬표 가져오기</h2></div>${source&&!uploading?'<button type="button" data-reset>작업 취소 · 원본 닫기</button>':''}</header><p>2-1A·2-1B처럼 여러 학생 사진이 한 장에 있는 자료를 불러오세요. 사진 영역을 잘라 현재 학급의 학생과 직접 연결합니다.</p><p class="notice">대상: <strong>${h(courseName)}</strong> · 등록 학생 ${students.length}명<br>원본은 이 브라우저에서만 처리합니다. OCR·AI·외부 분석을 사용하지 않습니다. 마지막 확인 후 선택한 학생의 240px 이하 JPEG 사진만 기존 비공개 학급 저장소에 업로드합니다. 원본 파일·이름표는 올리지 않도록 얼굴 영역만 지정하세요.</p>${!students.length?'<p class="notice warning">먼저 학번과 이름이 있는 명렬을 등록하세요. 사진 속 이름을 자동으로 만들거나 추측하지 않습니다.</p><button type="button" data-roster class="primary">명렬 관리로 이동</button>':''}${message?`<p class="notice warning" role="alert">${h(message)}</p>`:''}${phase==='pick'?`<label>1. 사진 명렬표 선택 (15MB 이하)<input data-sheet-file type="file" accept="image/jpeg,image/png,image/webp,application/pdf,.jpg,.jpeg,.png,.webp,.pdf" ${!students.length?'disabled':''}></label><p class="muted">JPEG·PNG·WebP·PDF 지원. PDF는 한 쪽씩 처리합니다. HWP·Word 파일은 PDF로 저장한 뒤 선택하세요. 새로고침·탭 이동·학급 변경 시 미저장 작업은 지워집니다.</p>`:''}${loading?'<p role="status">원본을 기기 안에서 여는 중입니다… <button type="button" data-reset>불러오기 취소</button></p>':''}${source&&phase==='edit'?editMarkup():''}${phase==='review'?reviewMarkup():''}${phase==='result'?`<h3>업로드 결과</h3><p role="status">${result.done}명 저장 확인. ${result.complete?'모두 저장했습니다.':result.unknown?'마지막 요청의 저장 여부가 미확인입니다. 중복 재시도하지 말고 서버 사진을 먼저 확인하세요.':'남은 사진은 업로드하지 않았습니다.'}</p>${result.error?`<p class="notice warning">${h(result.error.message)}</p>`:''}<button type="button" class="primary" data-reload>저장 결과 새로 확인</button>`:''}</section>`;
    if(source&&phase==='edit')draw();
  }
  function editMarkup(){const checked=photoMapping(regions,students);return `<h3>2. 사진 영역 지정 · 학생 연결</h3><p><strong>${h(file.name)}</strong> · ${source.width} × ${source.height}px · ${source.page}/${source.pages}쪽</p>${source.pages>1?`<div class="toolbar"><label>PDF 쪽<input data-page type="number" min="1" max="${source.pages}" value="${source.page}"></label><button type="button" data-page-apply>이 쪽 열기 (영역·연결 초기화)</button></div>`:''}<details class="sheet-grid-options" open><summary>규칙적인 명렬표: 격자 한 번에 만들기</summary><p>행·열 수와 표 전체 범위를 맞춘 뒤, 한 칸 안에서 얼굴 사진만 남길 범위를 정하세요. 이름·학번·빈칸은 포함하지 마세요. ‘격자 적용’은 기존 영역과 학생 연결을 초기화합니다.</p><div class="sheet-fields"><label>행<input type="number" min="1" max="20" data-grid="rows" value="${grid.rows}"></label><label>열<input type="number" min="1" max="20" data-grid="cols" value="${grid.cols}"></label></div><fieldset><legend>표 전체 범위 (원본 기준)</legend><div class="sheet-fields">${fields(grid.bounds,'bound')}</div></fieldset><fieldset><legend>한 칸 안의 사진 범위 (각 칸 기준)</legend><div class="sheet-fields">${fields(grid.inset,'inset')}</div></fieldset><button type="button" data-grid-apply>격자 적용 · 연결 초기화</button></details><p class="notice">불규칙한 명렬표는 아래 원본에서 얼굴을 드래그해 영역을 하나씩 추가하세요. 태블릿은 손가락으로 그릴 수 있습니다. 숫자 입력으로도 영역을 추가·수정할 수 있습니다.</p><div class="sheet-paper"><canvas data-sheet-canvas aria-label="사진 명렬표 원본. 아래 좌표 입력으로도 사진 영역을 지정할 수 있습니다."></canvas></div><div class="toolbar"><button type="button" data-add>사진 영역 직접 추가</button><button type="button" data-clear>모든 영역 지우기</button><span>${regions.length}개 영역 · 연결 ${checked.selected.length}명 · 제외 ${checked.skipped}개</span></div><div class="sheet-regions">${regions.map((r,i)=>`<article class="sheet-region"><div class="sheet-region-heading"><strong>${i+1}. ${h(r.label)}</strong><button type="button" data-remove="${i}" aria-label="${i+1}번 영역 삭제">영역 삭제</button></div><label>이 사진의 학생<select data-match="${i}" aria-label="${i+1}번 사진 학생 연결"><option value="">학생 선택 필요</option><option value="__skip__" ${r.skip?'selected':''}>제외 · 빈칸 또는 이번에 올리지 않음</option>${students.map(s=>`<option value="${h(s.id)}" ${!r.skip&&s.id===r.id?'selected':''}>${h(s.number)} ${h(s.name)}${existingIds.includes(s.id)?' (기존 사진 교체)':''}</option>`).join('')}</select></label><details ${openedRegionKey===r.key?'open':''}><summary>사진 범위 숫자로 수정</summary><div class="sheet-fields">${['x','y','width','height'].map((k,j)=>`<label>${['왼쪽','위쪽','너비','높이'][j]} %<input data-region="${i}" data-axis="${k}" type="number" min="0" max="100" step="0.1" value="${Number(r[k].toFixed(3))}"></label>`).join('')}</div></details></article>`).join('')}</div>${regions.length?`<p class="${checked.errors.length?'notice warning':'notice'}" role="status">${h(checked.errors.join(' ')||`연결 ${checked.selected.length}명. 이번에 연결하지 않는 재적 학생 ${checked.missing.length}명의 기존 사진은 유지됩니다.`)}</p>`:''}<button type="button" class="primary" data-preview ${!regions.length?'disabled':''}>잘린 사진으로 최종 대조</button>`;}
  function reviewMarkup(){const replaced=review.filter(p=>existingIds.includes(p.id)).length;return `<h3>3. 최종 미리보기 · 업로드 확인</h3><p><strong>${h(courseName)}</strong>에 ${review.length}명의 사진을 저장합니다. 기존 사진 교체 ${replaced}명. 제외한 영역과 원본 파일은 전송하지 않습니다.</p><p>각 얼굴·학번·이름과 학급을 다시 확인하세요. 이름표나 다른 학생이 사진에 들어 있으면 ‘영역·연결 수정’으로 돌아가 조정하세요.</p><div class="sheet-preview-grid">${review.map(p=>`<article><img src="${p.data}" alt="${h(labelOf(p))} 업로드할 사진"><strong>${h(labelOf(p))}</strong><small>${existingIds.includes(p.id)?'기존 사진을 교체합니다':'새 사진'}</small></article>`).join('')}</div><label class="sheet-confirm"><input data-confirm type="checkbox" ${confirmed?'checked':''} ${uploading?'disabled':''}> 대상 학급·모든 얼굴·학번·이름을 대조했고, 선택한 사진을 이 학급의 비공개 저장소에 업로드하는 데 동의합니다.</label><div class="toolbar"><button type="button" data-back ${uploading?'disabled':''}>영역·연결 수정</button><button type="button" class="primary" data-upload ${!confirmed||uploading?'disabled':''}>${uploading?'사진 저장 중…':`${review.length}명 사진 업로드`}</button></div>`;}
  async function openFile(next,page=1){
    if(uploading)return;loading=true;source=null;regions=[];review=[];confirmed=false;file=next;phase='pick';message='';render();
    try{const decoded=await loader.load(next,page);if(!decoded||!isCurrent())return;source=decoded;phase='edit';loading=false;render();}catch(e){if(!isCurrent())return;loading=false;file=null;error(e);}
  }
  function reset(){if(uploading)return;loader.clear();source=null;file=null;regions=[];review=[];confirmed=false;loading=false;phase='pick';message='';grid=defaultGrid();render();}
  function readGrid(){const next=structuredClone(grid);for(const n of root.querySelectorAll('[data-grid]'))next[n.dataset.grid]=Number(n.value);for(const kind of ['bound','inset'])for(const n of root.querySelectorAll(`[data-${kind}]`))next[kind==='bound'?'bounds':'inset'][n.dataset[kind]]=Number(n.value);return next;}
  async function click(e){const b=e.target.closest('button');if(!b||!root.contains(b)||uploading)return;message='';try{
    if(b.hasAttribute('data-reset'))return reset();
    if(b.hasAttribute('data-roster'))return options.onRoster();
    if(b.hasAttribute('data-reload'))return options.onReload();
    if(b.hasAttribute('data-page-apply'))return openFile(file,Number(q('[data-page]').value));
    if(b.hasAttribute('data-grid-apply')){grid=readGrid();regions=makeSheetGrid(grid);}
    else if(b.hasAttribute('data-add')){if(regions.length>=MAX_REGIONS)throw Error('사진 영역은 100개까지 추가할 수 있습니다.');regions.push({key:`manual-${++serial}`,label:'직접 지정',x:10,y:10,width:15,height:20,id:'',skip:false});}
    else if(b.hasAttribute('data-clear'))regions=[];
    else if(b.hasAttribute('data-remove'))regions.splice(Number(b.dataset.remove),1);
    else if(b.hasAttribute('data-back')){review=[];confirmed=false;phase='edit';}
    else if(b.hasAttribute('data-preview')){const checked=photoMapping(regions,students);if(checked.errors.length)throw Error(checked.errors.join(' '));review=checked.selected.map(p=>({...p,data:(options.crop??cropPortrait)(source,p)}));confirmed=false;phase='review';}
    else if(b.hasAttribute('data-upload')){
      if(!confirmed||options.isBusy?.())return;
      const upload=createPhotoUpload({courseId,version,students,getCurrent:options.getCurrent,preflight:options.preflight,save:options.save,isCurrent});
      uploading=true;render();
      await options.runWrite(async()=>{try{const uploaded=await upload.upload(review,confirmed);if(!isCurrent())return;result=uploaded;review=[];regions=[];loader.clear();source=null;file=null;phase='result';}catch(e){message=e.message;confirmed=false;}finally{uploading=false;if(isCurrent())render();}});
      return;
    }else return;
    render();
  }catch(e){error(e);}}
  function change(e){const t=e.target;if(uploading)return;
    if(t.hasAttribute('data-sheet-file')){const next=t.files?.[0];t.value='';if(next)void openFile(next);return;}
    if(t.hasAttribute('data-confirm')){confirmed=t.checked;q('[data-upload]').disabled=!confirmed;return;}
    if(t.hasAttribute('data-match')){const r=regions[Number(t.dataset.match)];r.skip=t.value==='__skip__';r.id=r.skip?'':t.value;render();return;}
    if(t.hasAttribute('data-region')){const r=regions[Number(t.dataset.region)],next={...r,[t.dataset.axis]:Number(t.value)};try{normalizedRegion(next);Object.assign(r,next);openedRegionKey=r.key;message='';render();}catch(e){error(e);}}
  }
  function point(e,canvas){const b=canvas.getBoundingClientRect();return {x:Math.max(0,Math.min(100,(e.clientX-b.left)/b.width*100)),y:Math.max(0,Math.min(100,(e.clientY-b.top)/b.height*100))};}
  function down(e){if(drag||!e.target.hasAttribute('data-sheet-canvas')||uploading||phase!=='edit'||e.button!==0)return;e.preventDefault();drag={from:point(e,e.target),to:null,pointer:e.pointerId};e.target.setPointerCapture(e.pointerId);}
  function move(e){if(!drag||e.pointerId!==drag.pointer)return;drag.to=point(e,e.target);draw();}
  function up(e){if(!drag||e.pointerId!==drag.pointer)return;const start=drag.from;drag=null;try{if(regions.length>=MAX_REGIONS)throw Error('사진 영역은 100개까지 추가할 수 있습니다.');const end=point(e,e.target);if(Math.abs(start.x-end.x)<.3||Math.abs(start.y-end.y)<.3){draw();return;}const r=dragRegion(start,end);regions.push({...r,key:`manual-${++serial}`,label:'직접 지정',id:'',skip:false});message='';render();}catch(e){error(e);}}
  function cancel(){drag=null;draw();}
  const events={click,change,pointerdown:down,pointermove:move,pointerup:up,pointercancel:cancel};for(const [name,fn] of Object.entries(events))root.addEventListener(name,fn);
  render();
  return {dispose(){disposed=true;loader.dispose();source=null;file=null;regions=[];review=[];drag=null;for(const [name,fn] of Object.entries(events))root.removeEventListener(name,fn);root.replaceChildren();},hasDraft:()=>!!source||loading};
}
